apiVersion: v1
kind: Service
metadata:
  name: {{ include "newtry.fullname" . }}-db
  labels:
    {{- include "newtry.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8081
      targetPort: http
      protocol: TCP
      name: http
  selector:
    type: "mongodb-service"
    {{- include "newtry.selectorLabels" . | nindent 4 }}
