apiVersion: v1
kind: Service
metadata:
  name: {{ include "newtry.fullname" . }}
  labels:
    {{- include "newtry.labels" . | nindent 4 }}
spec:
  type: {{ .Values.servicesfs.type }}
  ports:
    - port: 27017
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "newtry.selectorLabels" . | nindent 4 }}
